STRINGS = {
    "language.name": "English",
    "app.banner": "AI Document Generator",
    "app.mode": "interactive",
    "app.help_hint": "Type :help for commands, exit to quit",
    "prompt.label": "Prompt",
    "prompt.stop": "Stopping session",
    "help.commands": "Commands: :model <name>, :formats docx,pdf, :temperature 0.7, :top_p 0.9, :max_tokens 2048, :video_prompt text, :video_format mp4, :video_duration 8, :language en",
    "info.model_set": "Model set to {model}",
    "info.formats_set": "Formats set to {formats}",
    "info.temperature_set": "Temperature set to {temperature}",
    "info.top_p_set": "top_p set to {top_p}",
    "info.max_tokens_set": "Max tokens set to {max_tokens}",
    "info.unknown_command": "Unknown command",
    "info.available_models": "Available models:",
    "info.default_model_updated": "Default model updated to {model}",
    "info.language_set": "Language set to {language}",
    "info.video_prompt_set": "Video prompt set to {video_prompt}",
    "info.video_format_set": "Video format set to {video_format}",
    "info.video_duration_set": "Video duration set to {video_duration}",
    "info.invalid_language": "Unsupported language selection",
}
