STRINGS = {
    "language.name": "Polski",
    "app.banner": "Generator dokumentów AI",
    "app.mode": "tryb interaktywny",
    "app.help_hint": "Wpisz :help aby zobaczyć komendy, exit aby zakończyć",
    "prompt.label": "Zapytanie",
    "prompt.stop": "Kończenie sesji",
    "help.commands": "Komendy: :model <nazwa>, :formats docx,pdf, :temperature 0.7, :top_p 0.9, :max_tokens 2048, :video_prompt tekst, :video_format mp4, :video_duration 8, :language pl",
    "info.model_set": "Model zmieniono na {model}",
    "info.formats_set": "Formaty ustawiono na {formats}",
    "info.temperature_set": "Temperaturę ustawiono na {temperature}",
    "info.top_p_set": "top_p ustawiono na {top_p}",
    "info.max_tokens_set": "Limit tokenów ustawiono na {max_tokens}",
    "info.unknown_command": "Nieznane polecenie",
    "info.available_models": "Dostępne modele:",
    "info.default_model_updated": "Domyślny model zmieniono na {model}",
    "info.language_set": "Język ustawiono na {language}",
    "info.video_prompt_set": "Zapytanie wideo ustawiono na {video_prompt}",
    "info.video_format_set": "Format wideo ustawiono na {video_format}",
    "info.video_duration_set": "Długość wideo ustawiono na {video_duration}",
    "info.invalid_language": "Nieobsługiwany język",
}
