STRINGS = {
    "language.name": "Русский",
    "app.banner": "Генератор документов ИИ",
    "app.mode": "интерактивный режим",
    "app.help_hint": "Введите :help для списка команд, exit для выхода",
    "prompt.label": "Запрос",
    "prompt.stop": "Завершение сеанса",
    "help.commands": "Команды: :model <имя>, :formats docx,pdf, :temperature 0.7, :top_p 0.9, :max_tokens 2048, :video_prompt текст, :video_format mp4, :video_duration 8, :language ru",
    "info.model_set": "Модель изменена на {model}",
    "info.formats_set": "Форматы изменены на {formats}",
    "info.temperature_set": "Температура установлена на {temperature}",
    "info.top_p_set": "top_p установлено на {top_p}",
    "info.max_tokens_set": "Лимит токенов установлен на {max_tokens}",
    "info.unknown_command": "Неизвестная команда",
    "info.available_models": "Доступные модели:",
    "info.default_model_updated": "Модель по умолчанию изменена на {model}",
    "info.language_set": "Язык изменен на {language}",
    "info.video_prompt_set": "Видеозапрос установлен на {video_prompt}",
    "info.video_format_set": "Формат видео установлен на {video_format}",
    "info.video_duration_set": "Длительность видео установлена на {video_duration}",
    "info.invalid_language": "Неподдерживаемый язык",
}
