STRINGS = {
    "language.name": "Українська",
    "app.banner": "Генератор документів ШІ",
    "app.mode": "інтерактивний режим",
    "app.help_hint": "Введіть :help для списку команд, exit для виходу",
    "prompt.label": "Запит",
    "prompt.stop": "Зупинка сеансу",
    "help.commands": "Команди: :model <назва>, :formats docx,pdf, :temperature 0.7, :top_p 0.9, :max_tokens 2048, :video_prompt текст, :video_format mp4, :video_duration 8, :language uk",
    "info.model_set": "Модель змінено на {model}",
    "info.formats_set": "Формати змінено на {formats}",
    "info.temperature_set": "Температуру встановлено на {temperature}",
    "info.top_p_set": "top_p встановлено на {top_p}",
    "info.max_tokens_set": "Ліміт токенів встановлено на {max_tokens}",
    "info.unknown_command": "Невідома команда",
    "info.available_models": "Доступні моделі:",
    "info.default_model_updated": "Модель за замовчуванням змінено на {model}",
    "info.language_set": "Мову змінено на {language}",
    "info.video_prompt_set": "Відеозапит встановлено на {video_prompt}",
    "info.video_format_set": "Формат відео встановлено на {video_format}",
    "info.video_duration_set": "Тривалість відео встановлено на {video_duration}",
    "info.invalid_language": "Непідтримувана мова",
}
